server:
  port: 8125 # Zuul's default port

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
           allowedOrigins: http://localhost:5173
           allowedMethods:
           - GET
             POST
             PUT
             DELETE
      routes:
      - id: spyglass-spring-goals
        uri: lb://spyglass-spring-goals
        predicates:
          - Path=/goals/**
        filters:
        - name: CircuitBreaker # Provided by Resilience4J
          args:
            name: fallbackController 
            fallbackUri: forward:/cache/goals
      - id: spyglass-spring-users
        uri: lb://spyglass-spring-users
        predicates:
          - Path=/users/**
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka